
workspace:
  base: /go
  path: src/github.com/co0p/gowhisper

pipeline:
  build:
    image: golang
    commands:
      - go test -cover -v
      - go build -o gowhisper cmd/gowhisper/main.go
  scp:
    image: appleboy/drone-scp
    host: co0p.org
    username: root
    secrets: [ ssh_password ]
    target: /usr/local/gowhisper/
    source: 
     - gowhisper
     - clients.json
     - index.html
  ssh:
    image: appleboy/drone-ssh
    host: co0p.org
    username: root
    secrets: [ ssh_password ]
    port: 22
    script:
     - pkill -9 gowhisper
     - cd /usr/local/gowhisper
     - ./gowhisper -configurationFile ./clients.json -port 8888